package com.framgia.music_30.ultil;

public class Constant {
    public static final String GENRE_ALL_MUSIC = "allmusic";
    public static final String GENRE_ALL_AUDIO = "allaudio";
    public static final String GENRE_CLASSICAL = "classical";
    public static final String GENRE_COUNTRY = "country";
    public static final String GENRE_AMBIENT = "ambient";
    public static final String GENRE_ALTERNATIVEROCK = "alternativerock";
    public static final int TAB_GENRE = 0;
    public static final int TAB_MYSONG = 1;
    public static final int TAB_ARTIST = 2;
    public static final int TAB_TOTAL = 3;
    public static final String ID_SONG = "id";
    public static final String TITLE_SONG = "title";
    public static final String STREAM_URL = "stream_url";
    public static final String DOWNLOAD_URL = "stream_url";
    public static final String IMAGE_SONG = "artwork_url";
    public static final String TYPE_ONLINE = "online";
    public static final String TYPE_OFFLINE = "offline";
    public static final int LOOP_ALL = 0;
    public static final int LOOP_ONE = 1;
    public static final int NONE_LOOP = 2;
    public static final int NONE_SHUFFLE = 0;
    public static final int SHUFFLE = 1;
    public static final String NOTIFICATION_BACK_EVENT = "back_event";
    public static final String NOTIFICATION_PAUSE_EVENT = "pause_event";
    public static final String NOTIFICATION_NEXT_EVENT = "next_event";
    public static int REQUEST_CODE_NOTIFICATION = 123;
    public static int NOTIFICATION_ID = 1337;
    public static int NOTIFICATION_DOWNLOAD = 17;
    public static String CHANEL_ID = "CHANEL_ID";
    public static String DOWNLOAD_COMPLETE = "Download Success";
    public static String FOLDER_OFFLINE_MUSIC = "sdcard/mymusic";
    public static String DOWNLOADING = "Downloading...";
    public static String FILE_EXTEND = ".mp3";
    public static int SIZE_BYTE = 1024;
    public static int INPUTSTREAM_SIZE = 8192;
    public static int ONEHUNDERED = 100;
    public static int REQUEST_PERMISSION_CODE = 123;
}
